#!/bin/sh

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  if [ -f "$HOME/.local" ]; then
    echo "Delete default .local"
    rm -rf "$HOME/.local"
  fi

  if [ ! -d "$HOME/.config/local/share/yadm/repo.git" ]; then
    echo "Clone yadm repo"
    yadm clone --no-bootstrap https://github.com/Ci7rix/dotfiles.git
    yadm checkout "$HOME"
  fi

fi
