# Set plugin custom path
set-environment -g TMUX_PLUGIN_MANAGER_PATH $XDG_CACHE_HOME/tmux

if "test ! -d  $XDG_CACHE_HOME/tmux/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm $XDG_CACHE_HOME/tmux/tpm && $XDG_CACHE_HOME/tmux/tpm/bin/install_plugins'"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'

set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'dawn' # Options are 'main', 'moon' or 'dawn'
set -g @rose_pine_show_current_program 'on' # Forces tmux to show the current running program as window name
set -g @rose_pine_show_pane_directory 'on'

# Set options
set -g mouse on
set -g @scroll-speed-num-lines-per-scroll 1
set -g status-right-length 100
set -g renumber-windows on
set -s copy-command 'pbcopy'

bind-key -T copy-mode-vi WheelUpPane send-keys -N1 -X scroll-up
bind-key -T copy-mode-vi WheelDownPane send-keys -N1 -X scroll-down

# Replace default prefix
unbind C-b
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

# Keybindings
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run $XDG_CACHE_HOME/tmux/tpm/tpm
