#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  2
yabai -m config bottom_padding               2
yabai -m config left_padding                 2
yabai -m config right_padding                2
yabai -m config window_gap                   2

# rules
yabai -m rule --add app="^Préférences Système$" manage=off
yabai -m rule --add app="^Firefox$" title="^Ouverture de " manage=off
yabai -m rule --add app="^Finder$" title="^Infos sur " manage=off
yabai -m rule --add app="^Finder$" title="^Copier$" manage=off
yabai -m rule --add app="^Finder$" title="^Connexion au serveur$" manage=off
yabai -m rule --add app="^Finder$" title="^Copier$" manage=off
yabai -m rule --add app="^Programme d’installation$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off

echo "yabai configuration loaded.."
